apiVersion: apps/v1
kind: Deployment
metadata:
  name: rggfhjnv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rggfhjnv2
  template:
    metadata:
      labels:
        app: rggfhjnv2
    spec:
      containers:
      - image: okteto.dev/rggfhjnv2:latest
        name: rggfhjnv2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7accbfa9-d9a2-48dd-91ad-16adc442ee90"
        - name: Vless_Path
          value: "/7accbfa9-d9a2-48dd-91ad-16adc442ee90-vless"
        - name: Vmess_UUID
          value: "7accbfa9-d9a2-48dd-91ad-16adc442ee90"
        - name: Vmess_Path
          value: "/7accbfa9-d9a2-48dd-91ad-16adc442ee90-vmess"
        - name: Share_Path
          value: "/v2link"
